# List of patient IDs
# pilot1: '101' '103' '106' '107' '110' '111' '112' '113' '114' '115' '116' '201' '204' '205'
# CLEAR: 'p01' ... 'p18'
# Enable or disable debug mode
debug_mode: true

## ========================= Dataset ===============================
patient:
  - 'p01'
  - 'p02'
  - 'p03'
  - 'p04'
  - 'p05'


dataset: "clear" # Dataset name to use : "pilot01" "clear"
dataset_task: "m_sequence" # "flicker" or "m_sequence"
single_event_target: "target_9_8"

# Preprocessing
preprocessing_configs: {} #{'low_pass_filter': {'cutoff': 45, 'order': 5}}
load_preprocessed_data: true # Load preprocessed data from a file
save_preprocessed_data: true # Save preprocessed data to a file

# Feature extraction
save_features: true
load_features: false
feature_extraction_configs : {
        'time_n200': {'start_time': 150, 'end_time': 250},
        'time_p300': {'start_time': 250, 'end_time': 550},
        'time_post_p300': {'start_time': 550, 'end_time': 750},
        'frequency1': {'time_start': 0, 'end_time': 500},
        'frequency2': {'time_start': 250, 'end_time': 700}
    }
feature_transformation : "normalize"  # Options: normalize, standardize, None

# Feature selection
features_selection_method : "all"  # Options: all, corr, pre_selected
correlation_mode: "multi" # correlation based on single event or multi event Options: 'multi' or 'single'


# =========================== Training ===================================
cross_validation_mode: 'order'  # Options: 'single', 'order', 'kfold'
num_folds: 5
test_size: 0.2
load_pretrained_model: true # Load a pretrained model

# ============================= Model ====================================

method_list:
  - "xgboost"
#  - "fast_ldgd"
#  - "ldgd"

metric_list:
  - "accuracy"
  - "f1_score"
  - "precision"
  - "recall"

# LDGD Configs
data_dim : None
latent_dim : 3
num_inducing_points : 10
cls_weight : 1
use_gpytorch : True
shared_inducing_points : True

# Training LDGD
load_trained_model : False
batch_size : 100
num_epochs_train : 5000
num_epochs_test : 5000

